# Generated by Django 5.1 on 2025-08-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='game_entry_fee',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='season',
            name='players_per_team',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='season',
            name='playing_games',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='playing_skins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='skins_entry_fee',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='season',
            name='skins_type',
            field=models.CharField(choices=[('GROSS', 'Gross'), ('NET', 'Net')], default='GROSS', max_length=10),
        ),
    ]
