# Generated by Django 4.1.3 on 2023-03-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.golfer')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hole')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.score')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.week')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.IntegerField()),
                ('net', models.IntegerField()),
                ('round_points', models.FloatField()),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.golfer')),
                ('handicap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.handicap')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matchup')),
                ('points', models.ManyToManyField(to='main.points')),
                ('scores', models.ManyToManyField(to='main.score')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.week')),
            ],
            options={
                'unique_together': {('golfer', 'week')},
            },
        ),
    ]
