# Generated by Django 5.0 on 2024-03-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_round_total_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='round',
            name='golfer_matchup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.golfermatchup'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('golfer_matchup', 'week')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('golfer', 'week', 'hole')},
        ),
    ]
