# Generated by Django 5.2.4 on 2026-07-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_golfer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='field_avg_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='luck',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
