# Generated by Django 5.0 on 2024-03-24 21:13

from django.db import migrations, models

def truncate_datetime_to_date(apps, schema_editor):
    Week = apps.get_model('main', 'Week')
    for week in Week.objects.all():
        week.date = week.date.date()  # Truncates datetime to date
        week.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_round_unique_together_round_golfer_matchup_and_more'),
    ]

    operations = [
        migrations.RunPython(truncate_datetime_to_date),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(),
        ),
    ]
