# Generated by Django 5.0 on 2024-08-03 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_week_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
