# Generated by Django 5.0 on 2024-08-03 18:26
from django.db import migrations
import pytz

def correct_to_eastern(apps, schema_editor):
    Week = apps.get_model('main', 'Week')
    eastern = pytz.timezone('US/Eastern')
    utc = pytz.UTC

    for week in Week.objects.all():
        if week.date.tzinfo == utc:
            week.date = week.date.astimezone(eastern)
            week.save(update_fields=['date'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20240803_1425'),
    ]

    operations = [
         migrations.RunPython(correct_to_eastern),
    ]
