# Generated by Django 5.0 on 2024-08-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20240803_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='no_sub',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_golfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='main.golfer'),
        ),
    ]
