# Generated by Django 5.0 on 2024-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sub_no_sub_alter_sub_sub_golfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='num_scores',
            field=models.IntegerField(default=180),
            preserve_default=False,
        ),
    ]
