# Generated by Django 5.0.3 on 2024-08-20 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_week_num_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfermatchup',
            name='subbing_for_golfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbing_for_golfer', to='main.round'),
        ),
        migrations.CreateModel(
            name='RandomDrawnTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_team', to='main.team')),
                ('drawn_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawn_team', to='main.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.week')),
            ],
        ),
    ]
