# Generated by Django 5.0.3 on 2024-08-20 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_golfermatchup_subbing_for_golfer_randomdrawnteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfermatchup',
            name='subbing_for_golfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbing_for_golfer', to='main.golfer'),
        ),
    ]
