# Generated by Django 5.1 on 2025-07-13 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_round_is_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='subbing_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rounds_subbed_for', to='main.golfer'),
        ),
    ]
