# Generated by Django 5.1 on 2025-07-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_skin_entry_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfermatchup',
            name='is_teammate_subbing',
            field=models.BooleanField(default=False),
        ),
    ]
