# Generated by Django 5.1 on 2025-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_golfermatchup_is_teammate_subbing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfermatchup',
            name='is_A',
            field=models.BooleanField(db_column='is_a', default=False),
        ),
    ]
