# Generated by Django 5.1 on 2025-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_virtual_matchup_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfermatchup',
            name='is_virtual_matchup',
            field=models.BooleanField(default=False),
        ),
    ]
