# Generated by Django 5.1 on 2025-07-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_golfermatchup_is_virtual_matchup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfermatchup',
            name='is_virtual_matchup',
        ),
    ]
