# Generated by Django 5.1 on 2025-07-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_golfermatchup_is_virtual_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfermatchup',
            name='opponent_team_no_subs',
            field=models.BooleanField(default=False),
        ),
    ]
