# Generated by Django 5.1 on 2025-07-31 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_golfermatchup_opponent_team_no_subs'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_against', to='main.golfer'),
        ),
    ]
