# Generated by Django 5.1 on 2025-08-04 21:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_points_opponent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name'], 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='gameentry',
            options={'verbose_name': 'Game Entry', 'verbose_name_plural': 'Game Entries'},
        ),
        migrations.AlterModelOptions(
            name='golfer',
            options={'ordering': ['name'], 'verbose_name': 'Golfer', 'verbose_name_plural': 'Golfers'},
        ),
        migrations.AlterModelOptions(
            name='golfermatchup',
            options={'ordering': ['-week__date'], 'verbose_name': 'Golfer Matchup', 'verbose_name_plural': 'Golfer Matchups'},
        ),
        migrations.AlterModelOptions(
            name='handicap',
            options={'ordering': ['-week__date'], 'verbose_name': 'Handicap', 'verbose_name_plural': 'Handicaps'},
        ),
        migrations.AlterModelOptions(
            name='hole',
            options={'ordering': ['season', 'number'], 'verbose_name': 'Hole', 'verbose_name_plural': 'Holes'},
        ),
        migrations.AlterModelOptions(
            name='matchup',
            options={'ordering': ['-week__date'], 'verbose_name': 'Matchup', 'verbose_name_plural': 'Matchups'},
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'Point', 'verbose_name_plural': 'Points'},
        ),
        migrations.AlterModelOptions(
            name='randomdrawnteam',
            options={'ordering': ['-week__date'], 'verbose_name': 'Random Drawn Team', 'verbose_name_plural': 'Random Drawn Teams'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-week__date'], 'verbose_name': 'Round', 'verbose_name_plural': 'Rounds'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='skinentry',
            options={'verbose_name': 'Skin Entry', 'verbose_name_plural': 'Skin Entries'},
        ),
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ['-week__date'], 'verbose_name': 'Substitution', 'verbose_name_plural': 'Substitutions'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['-date'], 'verbose_name': 'Week', 'verbose_name_plural': 'Weeks'},
        ),
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.week'),
        ),
        migrations.AlterField(
            model_name='golfermatchup',
            name='subbing_for_golfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subbing_for_golfer', to='main.golfer'),
        ),
        migrations.AlterField(
            model_name='hole',
            name='handicap',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='hole',
            name='handicap9',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='hole',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='hole',
            name='par',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='hole',
            name='yards',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='points',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_against', to='main.golfer'),
        ),
        migrations.AlterField(
            model_name='points',
            name='points',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='golfer_matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.golfermatchup'),
        ),
        migrations.AlterField(
            model_name='round',
            name='gross',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='net',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_points',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='round',
            name='total_points',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_golfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='main.golfer'),
        ),
        migrations.AlterField(
            model_name='week',
            name='num_scores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='rained_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='gameentry',
            unique_together={('game', 'golfer', 'week')},
        ),
        migrations.AlterUniqueTogether(
            name='golfermatchup',
            unique_together={('week', 'golfer', 'opponent')},
        ),
        migrations.AlterUniqueTogether(
            name='handicap',
            unique_together={('golfer', 'week')},
        ),
        migrations.AlterUniqueTogether(
            name='hole',
            unique_together={('season', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='points',
            unique_together={('golfer', 'week', 'hole', 'opponent')},
        ),
        migrations.AlterUniqueTogether(
            name='randomdrawnteam',
            unique_together={('week', 'absent_team')},
        ),
        migrations.AlterUniqueTogether(
            name='sub',
            unique_together={('week', 'absent_golfer')},
        ),
    ]
