# Generated by Django 5.1 on 2025-08-17 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_phase3_enforce_layout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hole',
            options={'ordering': ['number'], 'verbose_name': 'Hole', 'verbose_name_plural': 'Holes'},
        ),
        migrations.RemoveConstraint(
            model_name='hole',
            name='uniq_config_number',
        ),
        migrations.AlterField(
            model_name='hole',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='main.courseconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='hole',
            unique_together={('config', 'number')},
        ),
    ]
