# Generated by Django 5.1 on 2025-08-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_league_season_league'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name'], 'verbose_name_plural': 'leagues'},
        ),
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=80, unique=True),
        ),
    ]
